CREATE DATABASE IF NOT EXISTS tinylinkdb;
USE tinylinkdb;

CREATE TABLE links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(8) UNIQUE NOT NULL,
  target_url TEXT NOT NULL,
  total_clicks INT DEFAULT 0,
  last_clicked DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
